create table public.departments (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(trim(name)) between 1 and 150),
    manager_name text not null default '',
    position_type text not null check (
        position_type in ('director', 'core', 'sub', 'tv_left', 'tv_right', 'ask_institute')
    ),
    sort_order integer not null default 0,
    created_at timestamptz not null default now()
);

create table public.staff (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(trim(name)) between 1 and 150),
    role text not null check (char_length(trim(role)) between 1 and 150),
    created_at timestamptz not null default now()
);

create table public.department_members (
    id bigint generated by default as identity primary key,
    department_id bigint not null references public.departments(id) on delete cascade,
    name text not null check (char_length(trim(name)) between 1 and 150),
    role text not null default '' check (char_length(trim(role)) <= 150),
    created_at timestamptz not null default now()
);

create table public.admin_users (
    user_id uuid primary key references auth.users(id) on delete cascade,
    created_at timestamptz not null default now()
);

create unique index if not exists departments_name_key
    on public.departments (name);

insert into public.departments (name, position_type, sort_order)
values
    ('BOARD OF DIRECTORS', 'director', 10),
    ('MANAGING DIRECTOR', 'director', 20),
    ('GENERAL MANAGER', 'director', 30),
    ('FINANCE ACCOUNTANT', 'core', 10),
    ('ROYAL TV GENERAL MANAGER', 'core', 20),
    ('HR MANAGER', 'core', 30),
    ('RICHCITY & ESTATES MANAGER', 'core', 40),
    ('A&A TRAVEL & TOURS MANAGER', 'core', 50),
    ('ASK FOODS MANAGERS', 'core', 60),
    ('A&A DRIVING SCH MANAGER', 'core', 70),
    ('PROGRAMS', 'tv_left', 10),
    ('CLIENT SERVICE MANAGER', 'tv_left', 20),
    ('MM', 'tv_left', 30),
    ('DIGITAL MARKETER AND BLOGGER', 'tv_left', 40),
    ('ROYAL TV ACCRA MANAGER', 'tv_left', 50),
    ('PRODUCTION MANAGER', 'tv_right', 10),
    ('HEAD OF IT BOP', 'tv_right', 20),
    ('STUDIO MANAGER', 'tv_right', 30),
    ('HEAD OF IT', 'tv_right', 40),
    ('PROPRIETOR', 'ask_institute', 10),
    ('HEAD OF SCHOOL', 'ask_institute', 20),
    ('TEACHERS', 'ask_institute', 30)
on conflict (name) do nothing;

alter table public.departments enable row level security;
alter table public.staff enable row level security;
alter table public.department_members enable row level security;
alter table public.admin_users enable row level security;

revoke all on public.admin_users from anon, authenticated;
grant select on public.departments, public.staff, public.department_members to anon, authenticated;
grant insert, update on public.departments, public.staff, public.department_members to authenticated;
grant delete on public.departments, public.staff, public.department_members to authenticated;
grant usage on sequence
    public.departments_id_seq,
    public.staff_id_seq,
    public.department_members_id_seq
to authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
        from public.admin_users
        where user_id = (select auth.uid())
    );
$$;

revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

create policy "Public can view departments"
    on public.departments for select to anon, authenticated
    using (true);
create policy "Admins can add departments"
    on public.departments for insert to authenticated
    with check ((select public.is_admin()));
create policy "Admins can update departments"
    on public.departments for update to authenticated
    using ((select public.is_admin()))
    with check ((select public.is_admin()));
create policy "Admins can delete departments"
    on public.departments for delete to authenticated
    using ((select public.is_admin()));

create policy "Public can view staff"
    on public.staff for select to anon, authenticated
    using (true);
create policy "Admins can add staff"
    on public.staff for insert to authenticated
    with check ((select public.is_admin()));
create policy "Admins can update staff"
    on public.staff for update to authenticated
    using ((select public.is_admin()))
    with check ((select public.is_admin()));
create policy "Admins can delete staff"
    on public.staff for delete to authenticated
    using ((select public.is_admin()));

create policy "Public can view department members"
    on public.department_members for select to anon, authenticated
    using (true);
create policy "Admins can add department members"
    on public.department_members for insert to authenticated
    with check ((select public.is_admin()));
create policy "Admins can update department members"
    on public.department_members for update to authenticated
    using ((select public.is_admin()))
    with check ((select public.is_admin()));
create policy "Admins can delete department members"
    on public.department_members for delete to authenticated
    using ((select public.is_admin()));

create or replace function public.set_department_manager(
    p_department_id bigint,
    p_manager_name text
)
returns void
language plpgsql
set search_path = ''
as $$
declare
    manager_member_id bigint;
begin
    if not (select public.is_admin()) then
        raise exception 'Administrator access required';
    end if;

    if p_manager_name is null or char_length(trim(p_manager_name)) not between 1 and 150 then
        raise exception 'Manager name must contain between 1 and 150 characters';
    end if;

    update public.departments
    set manager_name = trim(p_manager_name)
    where id = p_department_id;

    if not found then
        raise exception 'Department not found';
    end if;

    select id
    into manager_member_id
    from public.department_members
    where department_id = p_department_id and role = 'Manager'
    order by id
    limit 1;

    if manager_member_id is null then
        if trim(p_manager_name) <> '' then
            insert into public.department_members (department_id, name, role)
            values (p_department_id, trim(p_manager_name), 'Manager');
        end if;
    else
        update public.department_members
        set name = trim(p_manager_name)
        where id = manager_member_id;
    end if;
end;
$$;

revoke all on function public.set_department_manager(bigint, text) from public, anon;
grant execute on function public.set_department_manager(bigint, text) to authenticated;
